update Hibernate - fixes cryptic NPE message
When no Dialect was set, hibernate 6.5.2 would give a cryptic
stack trace with NPE.  7.1.0 gives a clear stack strace,
including the exception:

 org.postgresql.util.PSQLException: The connection attempt failed.

so the sysadmin now has a fighting chance.